title: Ronnie Lutaro
description: Portfolio and blog by Ronnie Lutaro
baseurl: ""
url: "https://ronnielutaro.github.io"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  blog:
    output: true
  projects:
    output: true
